app/main/models/blogs.py
class Blog:

    all_blogs = []

    def __init__(self,blog):
        self.blog


    def save_blog(self):
        Blog.all_blogs.append(self)


    @classmethod
    def clear_blogs(cls):
        Blog.all_blogs.clear()


    @classmethod
    def get_blogs(cls,id):

        response = []

        for blog in cls.all_blogs:
            response.append(blog)
            
            return response     

app/main/models/comments.py
class Comment:

    all_comments = []

    def __init__(self,comment):
        self.comment


    def save_comment(self):
        Comment.all_comments.append(self)


    @classmethod
    def clear_commentscls):
        Comments.all_comments.clear()


    @classmethod
    def get_pitches(cls,id):

        response = []

        for comment in cls.all_comments:
            response.append(comment)
            
            return response   

app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Blog',backref = 'user',lazy = "dynamic")

    @property  
    def password(self): 
        raise AttributeError('You cannot read the password attribute') 

    @password.setter 
    def password(self, password):   
        self.pass_secure = generate_password_hash(password)   

    def verify_password(self,password):   
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'{self.username}'


class Blog(db.Model):

    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    pitch_id = db.Column(db.Integer)
    blog_title = db.Column(db.String)
    pitch_title = db.Column(db.String)
    image_path = db.Column(db.String)
    pitch_review = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))    
    category = db.Column(db.String)
    # comments = db.relationship('Comments',backref = 'user',lazy = "dynamic")

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

class Comments(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment_id = db.Column(db.Integer)
    comment_title = db.Column(db.String)
    image_path = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))    
    category = db.Column(db.String)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    # @classmethod
    # def get_pitches(cls,id):
    #     pitches = Blog.query.filter_by(pitch=id).all()
    #     return pitches

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField, SelectField
from wtforms.validators import Required


class BlogForm(FlaskForm):
    pitch_title=TextAreaField('Write a blog title')
    blog_title = TextAreaField('Title')
    submit = SubmitField('Post')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CategoryForm(FlaskForm):
    pitch_title = TextAreaField('Write a category', validators=[Required()])
    submit = SubmitField('Submit')

class CommentPitch(FlaskForm):
    comment_title = TextAreaField('Write a comment',validators=[Required()])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from flask import Blueprint
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config_options
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()


# Initializing application
def create_app(config_name):
    app = Flask(__name__)


        # Creating the app configurations
    app.config.from_object(config_options[config_name])
    simple.init_app(app)

# configure UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint 
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    #setting config
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from flask_login import login_required, current_user
from .. import auth
from ..models import User,Blog,Comments
from .forms import UpdateProfile, BlogForm, CommentPitch
from .. import db,photos



#views
@main.route('/')
def index():
    '''
    View root page function that returns index page and its data
    '''
    title = 'PITCH'

    return render_template('index.html', title = title )   


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',uname=user.username))
    return render_template('profile/update.html',form =form)

@main.route('/new/blog',methods = ['GET','POST'])
@login_required
def add_category_blog():
    form = BlogForm()
    blog = Blog.query.filter_by().all()
    if form.validate_on_submit():
        blog = Blog(pitch_title=form.pitch_title.data,user=current_user)
        db.session.add(blog)
        db.session.commit()    
        return redirect(url_for('.index'))
    return render_template('blog.html',category_form = form,blog=blog)

@main.route('/posted/blogs',methods = ['GET','POST'])
@login_required
def posted_blogs():
    form = BlogForm()
    blog = Blog.query.filter_by().all()
    if form.validate_on_submit():
        blog = Blog(pitch_title=form.pitch_title.data,user=current_user)
        db.session.add(blog)
        db.session.commit()
        flash('It ahs been posted to posted blogs')    
        return redirect(url_for('.index'))
    return render_template('posted_blogs.html',category_form = form,blog=blog)

@main.route('/comment/blog',methods = ['GET','POST'])
@login_required
def add_comment_blog():
    form = CommentPitch()
    comment = Comments.query.filter_by().all()
    if form.validate_on_submit():
        comment = Comments(comment_title=form.comment_title.data)
        db.session.add(comment)
        db.session.commit()    
        return redirect(url_for('.index'))
    return render_template('blog.html',category_form = form,comment=comment)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!--Styles-->
{% block styles %}
    {{ super() }}
    <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}
{% endblock %}
<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container-fluid">
    {{wtf.quick_form(category_form)}}
    {{simplemde.load}}
</div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container-fluid">
    {{wtf.quick_form(comment_form_blog)}}
</div>

{% for item in comment %}
    {{item.blog_title}}
{% endfor %}

{% endblock %}

app/templates/fourOwfour.html
{% block content %}
<img src="https://cdn.mos.cms.futurecdn.net/PuXipAW3AXUzUJ4uYyxPKC.jpg" height="600px" width="1360px" alt="">
{% endblock %}

app/templates/index.html
{% extends 'base.html'%} {% import 'macros.html' as macro%} {% import "bootstrap/wtf.html" as wtf %}
<!DOCTYPE html>

<html>
{% block content %}

<head>
    <meta charset="utf-8"> {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> PITCH ALONG </title>
    {% endif %}
    <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico" />
    <style type="text/css">
        .category {
            margin-top: 70px;
            text-align: center;
        }

        .myButton {
            background-color: #B8044D;
            -moz-border-radius: 28px;
            -webkit-border-radius: 28px;
            border-radius: 28px;
            display: inline-block;
            cursor: pointer;
            color: #ffffff;
            font-family: Arial;
            font-size: 17px;
            padding: 5px 18px;
            text-decoration: none;
            margin: 10px;
            box-shadow: 0 0 0 2px white, 0 0 0 3px #B8044D;

        }

        .myButton a {
            color: #ffffff;
            font-family: Pacifico;
        }

        .myButton:hover a {
            text-decoration: none;
            color: #14F302;
            transition: color 0.8s ease;
        }

        .myButton:active {
            position: relative;
            top: 1px;
        }




        @import url(https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css);
        @import url(https://fonts.googleapis.com/css?family=Lato:400,300,900);

        body {
            background-color: #0096D6;
        }

        html,
        body {
            width: 100%;
            height: 100%;
            margin: 0;
        }

        body {
            font-family: 'Lato', sans-serif !important;
            font-size: 13pt !important;
            font-weight: 300 !important;
        }

        .container-fluid {
            padding-right: 0px !important;
            padding-left: 0px !important;
        }

        #myPageContent,
        section {
            height: 100% !important;
            width: 100% !important;
        }


        /* Slider */
        #textSlider.row {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 100% !important;
        }

        #textSlider div {
            color: #FFF;
            font-family: 'Lato', sans-serif;
            text-transform: uppercase;
        }

        .iamCol {
            text-align: right;
            float: left;
            font-weight: 300;
            font-size: 30pt;
        }

        .iamCol p:nth-child(2) {
            margin-top: -20pt !important;
        }

        .slideCol {
            text-align: left;
            overflow: hidden;
            font-weight: 900;
            font-size: 15pt;
            display: block;
            white-space: nowrap;
        }

        .slideCol p {
            margin: 0px !important;
        }

        .scroller {
            height: 70pt;
            line-height: 70pt;
            overflow: hidden;
        }

        .scroller .inner {
            animation: 10s normal infinite running scroll;
        }

        @keyframes scroll {
            0% {
                margin-top: 0px;
            }
            15% {
                margin-top: 0px;
            }

            25% {
                margin-top: -70pt;
            }
            40% {
                margin-top: -70pt;
            }

            50% {
                margin-top: -140pt;
            }
            65% {
                margin-top: -140pt;
            }

            75% {
                margin-top: -210pt;
            }
            90% {
                margin-top: -210pt;
            }

            100% {
                margin-top: 0px;
            }
        }


        /*==========  Mobile First Method  ==========*/

        /* Custom, iPhone Retina */
        @media only screen and (min-width: 320px) and (max-width: 479px) {
            #textSlider.row {
                margin-right: 0px !important;
                margin-left: 0px !important;
            }
            .iamCol {
                text-align: center;
                font-size: 20pt;
            }
            .iamCol p {
                display: inline !important;
            }
            .slideCol {
                font-size: 25pt;
                text-align: center;
                margin-top: -20px;
            }
        }

        /* Extra Small Devices, Phones */
        @media only screen and (min-width: 480px) and (max-width: 765px) {
            #textSlider.row {
                margin-right: 0px !important;
                margin-left: 0px !important;
            }
            .iamCol {
                text-align: center;
                font-size: 25pt;
            }
            .iamCol p {
                display: inline !important;
            }
            .slideCol {
                font-size: 38pt;
                text-align: center;
                margin-top: -20px;
            }
        }

        /* Small Devices, Tablets */
        @media only screen and (min-width: 768px) and (max-width: 992px) {
            #textSlider.row {
                margin-right: 0px !important;
                margin-left: 0px !important;
            }
            .iamCol {
                text-align: center;
                font-size: 30pt;
            }
            .iamCol p {
                display: inline !important;
            }
            .slideCol {
                font-size: 50pt;
                text-align: center;
                margin-top: 5px;
            }
        }

        /* Medium Devices, Desktops */
        @media only screen and (min-width: 992px) and (max-width: 1200px) {
            #textSlider.row {
                margin-right: 0px !important;
                margin-left: 0px !important;
            }
            .iamCol {
                text-align: right;
                font-size: 30pt;
            }
            .slideCol {
                font-size: 55pt;
                text-align: left;
            }
        }
    </style>

</head>



<body style="background-image:url(https://images.unsplash.com/photo-1521798948753-02f843fd3e5d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7a2059a47213b313bb76f8996273d794&auto=format&fit=crop&w=750&q=80);background-size: cover;background-repeat: no-repeat;">


    <div class="category">
        <button type="button" class="myButton"><a href="/new/blog">Create Blog</a></button>
        <button type="button" class="myButton"><a href="/posted/blogs">Posted Blogs</a></button>
    </div>
    
    


    <div id="myPageContent" class="container-fluid">
        <section id="home">




            <div id="textSlider" class="row">
                <div class="col-xs-12 col-sm-12 col-md-3 col-lg-4 iamCol">
                    <p>Blog</p>
                    <p>tip</p>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 slideCol">
                    <div class="scroller">
                        <div class="inner">
                            <p>Speak confidently about your product,</p>
                            <p>but be able to admit when you need more information,</p>
                            <p>and getit to the people you're pitching</p>
                            <p>quickly after the meeting.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section </div>
        <!-- <p>Blog tip: Speak confidently about your product, but be able to admit when you need more information, and get
            it to the people you're pitching quickly after the meeting. </p> -->
        {% endblock%}


</body>


</html>

app/templates/macros.html
<!-- {% macro displayblogs(pitch_list) %}
    {% for blog in pitch_list %}
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 blog-card">
        
        <p> {{ blog.blog | truncate(30) }}</p>
    </div>
    {% endfor %}
{% endmacro %} -->

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <img src="https://png.icons8.com/windows/50/ffffff/idea-sharing.png">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="/">Home</a>

        </div>


        <ul class="nav navbar-nav navbar-right">

            {% if current_user.is_authenticated %}
            <li style="color:white;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>



    </div>

</div>
<style>
</style>

app/templates/new_pitch.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<div class="container">
    {{ wtf.quick_form(pitch_form) }}
</div>

{% if user.bio %}
<p> {{user.bio}}</p>
{%else%}
<p> {{user.username| capitalize}} has no bio </p>
{% endif %} 
{% endblock %}

app/templates/posted_blogs.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block content %}
<style type="text/css">
    .blogs {
        border-left: 6px solid #A11635;
        background-color: lightgrey;
        padding-bottom: 10px;
    }

    .comment {
        color: #ffffff
    }
</style>
<div class="row">
    <div class="col-md-4">
        <div class="blogs">
            {% for item in blog %}
            <p><span><img src="https://png.icons8.com/windows/50/1abc9c/administrator-male.png"></span>{{item.user}}</p>
            <p><span><img src="https://png.icons8.com/windows/50/1abc9c/administrator-male.png"></span>{{item.blog_title}}</p>
            <p><span><img src="https://png.icons8.com/dotty/50/EC1A61/tag-window.png"></span>{{item.pitch_title}}</p>
            <p><span><img src="https://png.icons8.com/ios/50/F9254E/watch-filled.png"></span>{{item.posted}}</p>

            <button class="btn btn-primary" type="button">
                <a class="comment" href="/comment/blog"></a><span class="badge"><span class="glyphicon glyphicon-thumbs-up"></span></span>
            </button>

            <button class="btn btn-primary" type="button">
                <a class="comment" href="/comment/blog"></a><span class="badge"><span class="glyphicon glyphicon-thumbs-down"></span></span>
            </button>

            <button class="btn btn-primary" type="button">
                <a class="comment" href="/comment/blog">Comment </a><span class="badge"><span class="glyphicon glyphicon-comment"></span></span>
            </button>
            {% endfor%}
        </div>
    </div>
</div>



{% for item in comment %} {{item.comment_title}} {% endfor %}{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  {% if user == current_user %}
  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

    <input type="file"  name="photo"  required>
    <input type="submit">
  </form>
    {% endif %}
</div>
</div>
</div>


{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}